HW15/config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
  resources :categories, only: %i[index show]
  resources :products, only: %i[index show]
  resources :lineitems, only: %i[create destroy]
  resources :orders, only: %i[create show index]
  get '/cart', to: 'carts#show', as: :cart
  post 'lineitems/:id/add' => "lineitems#add_quantity", as: "lineitem_add"
  post 'lineitems/:id/reduce' => "lineitems#reduce_quantity", as: "lineitem_reduce"
  post 'orders/:id/pay' => "orders#pay", as: "order_pay"
end

HW15/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

HW15/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

HW15/app/models/cart.rb
class Cart < ApplicationRecord
  has_many :lineitems, dependent: :nullify
  has_one :order

  def add_product(product)
    line_item = lineitems.find_by(product: product)
    if line_item and product.price == line_item.price
      line_item.quantity += 1
      line_item.save
    else
      lineitems.create(product: product, quantity: 1, price: product.price)
    end
  end

  def delete_product(product)
    line_item = lineitems.find_by(product: product)
    if line_item
      line_item.destroy
    end
  end

  def total_price
    sum = 0
    self.lineitems.each do |item|
      sum+= item.price * item.quantity
    end
    return sum
  end
end

HW15/app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy

end

HW15/app/models/lineitem.rb
class Lineitem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  validates :quantity, numericality: { greater_than_or_equal_to: 1}
end

HW15/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart
  belongs_to :user

  enum :status, %i[unpaid paid]
end

HW15/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :lineitems, dependent: :nullify
  has_one_attached :image

  after_create_commit -> { broadcast_prepend_to "products", partial: "products/turbo_product", locals: { product: self }, target: "products" }
end

HW15/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :nullify
end

HW15/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def initialize
    super
    @all_categories = Category.all
  end

  LotteryWinnersWorker.set(wait: 1.month).perform_async

  def current_cart
    Cart.find(cookies[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    cookies[:cart_id] = cart.id
    cart
  end

  helper_method :current_cart
end

HW15/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show; end
end

HW15/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def initialize
    super
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products
  end

  def index
  end

  private

    def category_params
      params.permit(:title)
    end

end

HW15/app/controllers/lineitems_controller.rb
class LineitemsController < ApplicationController
  def create
    product = Product.find(params[:product_id])
    current_cart.add_product(product)

    render partial: 'products/add_card'
    # redirect_to cart_path, notice: "#{product.name} was added to the Cart"
  end

  def destroy
    lineitem = Lineitem.find(params[:id])
    lineitem.destroy

    redirect_to cart_path, notice: "Product was deleted from the Cart"
  end

  def add_quantity
    lineitem = Lineitem.find(params[:id])
    lineitem.quantity += 1
    lineitem.save
    redirect_to cart_path
  end

  def reduce_quantity
    lineitem = Lineitem.find(params[:id])
    if lineitem.quantity > 1
      lineitem.quantity -= 1
    end
    lineitem.save
    redirect_to cart_path
  end
end

HW15/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    order = current_user.orders.create(cart: current_cart, status: 0)
    cookies.delete(:cart_id)

    redirect_to order_path(order), notice: "Order was created"
  end

  def show
    @order = current_user.orders.find(params[:id])
  end

  def index
    @orders = current_user.orders.all
  end

  def pay
    order = current_user.orders.find(params[:id])
    order.status = 1
    order.save
    UserMailer.send_order(current_user, order).deliver_now
    redirect_to order_path(order), notice: "Order was paid"
  end
end

HW15/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def initialize
    super
  end

  def index
    @products = Product.all
    @products = Category.find(params[:category_id]).products if params[:category_id].present?
  end

  def show
    @product = Product.find(params[:id])
  end

  private

    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end

end

HW15/app/helpers/application_helper.rb
module ApplicationHelper
end

HW15/app/views/carts/show.html.erb
<section class="py-5 bg-light">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <% if current_cart.lineitems.any? %>
        <table class="table">
          <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Image</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
            <th scope="col"></th>
          </tr>
          </thead>
          <tbody>
          <% current_cart.lineitems.each_with_index do |line_item, index| %>
            <tr>
              <td> <%= index +1 %></td>
              <td><%= image_tag(line_item.product.image, :size => "200x200") %> </td>
              <td><%= line_item.product.name %></td>
              <td><%= line_item.product.description %></td>
              <td><%= line_item.quantity %> </td>
              <td><%= number_to_currency(line_item.price) %></td>
              <td><%= button_to "+1", lineitem_add_path(:id => line_item.id), method: :post, class: 'btn btn-primary' %>
                <%= button_to "-1", lineitem_reduce_path(:id => line_item.id), method: :post, class: 'btn btn-primary' %>
              <%= button_to 'Delete from card',  lineitem_path(id: line_item.id), :method => :delete , class: 'btn btn-primary' %><td>
            </tr>
          <% end %>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><b>Total <%= number_to_currency(current_cart.total_price) %></b><td>
          </tr>
          </tbody>
        </table>
        <% if user_signed_in? %>
          <%= button_to 'Checkout', orders_path, class: 'btn btn-primary' %>
        <% end %>
      <% else %>
        <p>Current Cart is empty</p>
      <% end %>
    </div>
  </div>
</section>

HW15/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>Shop Item - Start Bootstrap Template</title>
  <!-- Favicon-->
  <link rel="icon" type="image/x-icon" href="favicon.ico" />
  <!-- Bootstrap icons-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container px-4 px-lg-5">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
        <li class="nav-item"><a class="nav-link active" aria-current="page" <%= link_to 'Home', root_path %></a></li>
        <% @all_categories.each do |category| %>
          <li class="nav-item"><a class="nav-link" <%= link_to category.title, products_path(category_id: category.id) %></a></li
        <% end %>
        <li class="nav-item dropdown">
        </li>
      </ul>
      <form class="d-flex">
        <% if user_signed_in? %>
          <li class="btn btn-outline-dark"><a href=<%=cart_path %> <span class="glyphicon glyphicon-shopping-cart"></span> Cart</a></li>
          <li class="btn btn-outline-dark"><%= link_to 'Orders', orders_path %></li>

          <li class="btn btn-outline-dark"><%= link_to 'Edit profile', edit_user_registration_path %></li>
          <li class="btn btn-outline-dark"><%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %></li>
          <li class="btn btn-outline-dark"><a>Logged in as <strong><%= current_user.email %></strong></a>></li>
        <% else %>
          <li class="btn btn-outline-dark"><%= link_to "Sign up", new_user_registration_path %></li>
          <li class="btn btn-outline-dark"><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </form>
    </div>
  </div>
</nav>
<!-- Product section-->
<%=yield %>

<!-- Footer-->
<footer class="py-5 bg-dark">
  <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

HW15/app/views/orders/index.html.erb
<section class="py-5 bg-light">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <% if user_signed_in? %>
        <% @orders.each_with_index do |order, index| %>
          <h1>Order #<%= order.id %> status: <%=order.status %></h1>
          <table class="table">
            <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Image</th>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
              <th scope="col">Quantity</th>
              <th scope="col">Price</th>
              <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            <% order.cart.lineitems.each_with_index do |line_item, index| %>
              <tr>
                <td> <%= index +1 %></td>
                <td><%= image_tag(line_item.product.image, :size => "200x200") %> </td>
                <td><%= line_item.product.name %></td>
                <td><%= line_item.product.description %></td>
                <td><%= line_item.quantity %> </td>
                <td><%= number_to_currency(line_item.price) %></td>
              </tr>
            <% end %>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td><b>Total <%= number_to_currency(order.cart.total_price) %></b><td>
            </tr>
            </tbody>
          </table>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

HW15/app/views/orders/show.html.erb
<% if user_signed_in? %>
  <h1>Order #<%= @order.id %> status: <%=@order.status %></h1>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Image</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <% @order.cart.lineitems.each_with_index do |line_item, index| %>
      <tr>
        <td> <%= index +1 %></td>
        <td><%= image_tag(line_item.product.image, :size => "200x200") %> </td>
        <td><%= line_item.product.name %></td>
        <td><%= line_item.product.description %></td>
        <td><%= line_item.quantity %> </td>
        <td><%= number_to_currency(line_item.price) %></td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td><b>Total <%= number_to_currency(@order.cart.total_price) %></b><td>
    </tr>
    </tbody>
  </table>
  <%= button_to 'Pay', order_pay_path(id: @order.id), class: 'btn btn-primary' %>
<% end %>

HW15/app/views/products/_add_card.html.erb
<%= turbo_frame_tag 'add_card' do %>
  <%= button_to 'Put in card', lineitems_path(product_id: @product.id), class: 'btn btn-primary' %>
<% end %>

HW15/app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= product.image %>
  </p>

</div>

HW15/app/views/products/_turbo_product.html.erb
<turbo-stream action="prepend" target="products">
  <template>
    <turbo-frame id="product_123">
      <div id="<%= dom_id product %>">
        <p>
          <strong>Name:</strong>
          <%= product.name %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= product.description %>
        </p>

        <p>
          <strong>Price:</strong>
          <%= product.price %>
        </p>

        <p>
          <strong>Image:</strong>
          <%= product.image %>
        </p>

      </div>
    </turbo-frame>
  </template>
</turbo-stream>

HW15/app/views/products/index.html.erb
<!-- Related items section-->
<section class="py-5 bg-light">
  <%= turbo_stream_from "products" %>
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <% @products.each do |product| %>
        <div class="col mb-5">
          <div class="card h-100">
            <!-- Sale badge-->
            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
            <!-- Product image-->
            <%= image_tag(product.image)%>
            <!-- Product details-->
            <div class="card-body p-4">
              <div class="text-center">
                <!-- Product name-->
                <h5 class="fw-bolder"><%= product.name %></h5>
                <!-- Product reviews-->
                <div class="d-flex justify-content-center small text-warning mb-2">
                  <div class="bi-star-fill"></div>
                  <div class="bi-star-fill"></div>
                  <div class="bi-star-fill"></div>
                  <div class="bi-star-fill"></div>
                  <div class="bi-star-fill"></div>
                </div>
                <%= number_to_currency(product.price) %>
              </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
              <%#= link_to "Show this product", product %>
              <div class="text-center"><a class="btn btn-outline-dark mt-auto" <%= link_to "Add to card", product %></a></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

HW15/app/views/products/show.html.erb
<!-- Product section-->
<section class="py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="row gx-4 gx-lg-5 align-items-center">
      <div class="col-md-6"><%= image_tag(@product.image) %></div>
      <div class="col-md-6">
        <div class="small mb-1"></div>
        <h1 class="display-5 fw-bolder"><%= @product.name %></h1>
        <div class="fs-5 mb-5">
          <!--          <span class="text-decoration-line-through">$45.00</span>-->
          <span><%= number_to_currency(@product.price) %></span>
        </div>
        <p class="lead"><%= @product.description %></p>
        <div class="d-flex">
          <%= turbo_frame_tag 'add_card' do %>
            <%= button_to 'Add to card', lineitems_path(product_id: @product.id), class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

HW15/app/views/templates/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
      /* Remove the navbar's default rounded borders and increase the bottom margin */
      .navbar {
          margin-bottom: 50px;
          border-radius: 0;
      }

      /* Remove the jumbotron's default bottom margin */
      .jumbotron {
          margin-bottom: 0;
      }

      /* Add a gray background color and some padding to the footer */
      footer {
          background-color: #f2f2f2;
          padding: 25px;
      }
  </style>
</head>
<body>
<div class="jumbotron">
  <div class="container text-center">
    <h1>Cat's online Store</h1>
  </div>
</div>

HW15/app/views/templates/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <% categories.each do |category| %>
          <% if category == @category %>
            <li class="active"><a href="<%= category_path(category) %>"><%= category.title %></a></li>
          <% else %>
            <li><a href="<%= category_path(category) %>"><%= category.title %></a></li>
          <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> Cart</a></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %></li>
          <li><a>Logged in as <strong><%= current_user.email %></strong></a>></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>